### ISSUE TITLE
Error in Nordic Semiconductor DFU: No Trigger Interface Found and TypeError on Serial DFU Update

### ISSUE THREAD

**Issue by marcolucc** [koenvervloesem/openhaystack-zephyr#6]
I'm working on MacOS 11 bigsur, and BBC microbit v2.2 (nfr52)
The specified serial port (/dev/tty.usbmodem14102) is correct and accessible.
python3.10
nrfutil 6.1.7

I encountered an issue while attempting to perform a Device Firmware Update (DFU) using the Nordic Semiconductor nRFutil tool. The update is being done over a USB serial connection using the following command:

`nrfutil dfu usb-serial -pkg openhaystack.zip -p /dev/tty.usbmodem14102
`
However, during the update process, I received the following error messages:
`
openhaystack-zephyr % nrfutil dfu usb-serial -pkg openhaystack.zip -p /dev/tty.usbmodem14102
  [------------------------------------]    0%2023-08-29 15:03:50,312 No trigger interface found for device with serial number: 990636020005282066217b1b4ded8f5e000000006e052820, Product ID: 0x204 and Vendor ID: 0xD28

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/nrfutil", line 8, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nordicsemi/__main__.py", line 1032, in usb_serial
    do_serial(package, port, connect_delay, flow_control, packet_receipt_notification, baud_rate, serial_number, False,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nordicsemi/__main__.py", line 988, in do_serial
    dfu.dfu_send_images()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nordicsemi/dfu/dfu.py", line 127, in dfu_send_images
    self._dfu_send_image(self.manifest.application)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nordicsemi/dfu/dfu.py", line 88, in _dfu_send_image
    self.dfu_transport.open()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nordicsemi/dfu/dfu_transport_serial.py", line 217, in open
    self.__get_mtu()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nordicsemi/dfu/dfu_transport_serial.py", line 366, in __get_mtu
    self.mtu = struct.unpack('<H', bytearray(response))[0]
TypeError: cannot convert 'NoneType' object to bytearray
`

**Comment by koenvervloesem** [comment]
For the micro:bit v2, the Zephyr docs suggest to use `west flash` to flash the firmware: https://docs.zephyrproject.org/latest/boards/arm/bbc_microbit_v2/doc/index.html

Does that work?

**Comment by marcolucc** [comment]
No, same issue 

```
openhaystack-zephyr % west build -b bbc_microbit_v2 app         
Traceback (most recent call last):
  File "/usr/local/bin/west", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/west/app/main.py", line 1085, in main
    app.run(argv or sys.argv[1:])
  File "/usr/local/lib/python3.11/site-packages/west/app/main.py", line 236, in run
    self.load_manifest()
  File "/usr/local/lib/python3.11/site-packages/west/app/main.py", line 254, in load_manifest
    self.manifest = Manifest.from_topdir(topdir=self.topdir,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/west/manifest.py", line 1193, in from_topdir
    return Manifest(topdir=topdir, config=config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/west/manifest.py", line 1485, in __init__
    current_data=validate(self._ctx.current_data))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/west/manifest.py", line 541, in validate
    as_dict = _load(data)
              ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/west/manifest.py", line 207, in _load
    return yaml.safe_load(data)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
                           ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute ‘Hashable'
```


```

 openhaystack-zephyr % west flash
Traceback (most recent call last):
  File "/usr/local/bin/west", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/west/app/main.py", line 1085, in main
    app.run(argv or sys.argv[1:])
  File "/usr/local/lib/python3.11/site-packages/west/app/main.py", line 236, in run
    self.load_manifest()
  File "/usr/local/lib/python3.11/site-packages/west/app/main.py", line 254, in load_manifest
    self.manifest = Manifest.from_topdir(topdir=self.topdir,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/west/manifest.py", line 1193, in from_topdir
    return Manifest(topdir=topdir, config=config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/west/manifest.py", line 1485, in __init__
    current_data=validate(self._ctx.current_data))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/west/manifest.py", line 541, in validate
    as_dict = _load(data)
              ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/west/manifest.py", line 207, in _load
    return yaml.safe_load(data)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
                           ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Hashable'
```

**Comment by koenvervloesem** [comment]
I just tried this with a BBC micro:bit v2, on a cleanly initialized version of this repository, and building and flashing just works. This looks like a problem in your Zephyr development environment. Did you follow all steps in Zephyr's [Getting Started](https://docs.zephyrproject.org/latest/develop/getting_started/index.html) guide? And are you able to build and flash the [Blinky](https://docs.zephyrproject.org/latest/samples/basic/blinky/README.html#blinky-sample) sample?

**Comment by koenvervloesem** [comment]
Closing because no response after a month, and this looks like a problem with the development environment.
